<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.8.0" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.8.0" />
    <PackageReference Include="WEBASE.EF" Version="2024.5.30.1920" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SspUis.BizLogicLayer\SspUis.BizLogicLayer.csproj" />
  </ItemGroup>

</Project>
