using Microsoft.AspNetCore.Mvc.RazorPages;
using SspUis.BizLogicLayer.Doc.MonoApplicationServices;
using SspUis.BizLogicLayer.ReportServices.Main;
using SspUis.BizLogicLayer.ReportServices.Main.QueryObjects;
using SspUis.BizLogicLayer.ReportServices.Main.ReportDtos.Memship;
using SspUis.BizLogicLayer.ReportServices.Main.ReportDtos.Partner;
using SspUis.DataLayer;
using SspUis.DataLayer.EfClasses;
using SspUis.DataLayer.EfClasses.Exapidata;
using SspUis.DataLayer.EfClasses.Memship;
using SspUis.DataLayer.EfClasses.Report;
using SspUis.DataLayer.EfClasses.Report.Func;
using SspUis.Integration.Bandlik.Models;
using SspUis.Integration.BankCredit.Models;
using StatusGeneric;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WEBASE.Models;

namespace SspUis.BizLogicLayer.ReportServices
{
    public interface IReportService : IStatusGenericHandler
    {
        List<MemshipNewContractorReportDto> GetMemshipNewContractorReportList(MemshipNewContractorReportDtoFilter option);
        List<PrtnApplicationAndContractInfoDto> GetPrtnApplicationAndContractInfo(PrtnApplicationAndContractInfoDtoFilter filter);
        IQueryable<PrtnEmploymentGraphReportNewDto> GetPrtnEmploymentGraphNewReport(PrtnDocumentSortFilterOptions filter);
        PagedResult<PrtnEmploymentGraphReportNewDto> GetPrtnEmploymentGraphNewReportWithPagination(PrtnDocumentSortFilterOptions filter);
        Stream PrintPrtnEmploymentGraphNewReport(PrtnDocumentSortFilterOptions filter);
        IQueryable<PrtnApplicationByPetitionInfoDto> GetPrtnApplicationByPetitionInfo(PrtnDocumentSortFilterOptions filter);
        PagedResult<PrtnApplicationByPetitionInfoDto> GetPrtnApplicationByPetitionInfoWithPagination(PrtnDocumentSortFilterOptions filter);
        Stream PrintPrtnApplicationByPetitionInfo(PrtnDocumentSortFilterOptions filter);
        IQueryable<PrtnApplicationByContractInfoDto> GetPrtnApplicationByContractNewInfo(PrtnDocumentSortFilterOptions filter);
        PagedResult<PrtnApplicationByContractInfoDto> GetPrtnApplicationByContractNewInfoWithPagination(PrtnDocumentSortFilterOptions filter);
        Stream PrintPrtnApplicationByContractNewInfo(PrtnDocumentSortFilterOptions filter);
        IQueryable<PrtnApplicationByFullInfoDto> GetPrtnApplicationByFullInfo(PrtnDocumentSortFilterOptions filter);
        PagedResult<PrtnApplicationByFullInfoDto> GetPrtnApplicationByFullInfoWithPagination(PrtnDocumentSortFilterOptions filter);
        Stream PrintPrtnApplicationByFullInfo(PrtnDocumentSortFilterOptions filter);
        PagedResult<PrtnApplicationAndContractInfoDto> GetPrtnApplicationAndContractInfoPaged(PrtnDocumentSortFilterOptions filter);
        List<MemshipReportByPersonType> GetMemshipReportByPersonTypes(MemshipReportByPersonTypeFilter filter);
        //Task<List<MemshipContractPaidDto>> GetMemshipContract(MemshipContractPaidDtoFilter filter);
        List<ContractorCategoryDto> GetContractorCategoryType(ContractorCategoryDtoFilter options);
        List<MemshipContractPaidDto> GetMemshipContract(MemshipContractPaidDtoFilter filter);
        List<MemshipDocsInfoDto> GetMemshipDocsInfo(MemshipDocsInfoDtoFilter options);
        List<MemshipReportByOrganizationDto> GetMemshipReportByOrganization(MemshipReportByOrganizationDtoFilter filter);
        List<PrtnCreditDemandInfoDto> GetPrtnCreditDemandInfo(PrtnCreditDemandInfoDtoFilter filter);
        PagedResult<PrtnCreditDemandInfoDto> GetPrtnCreditDemandInfoPaged(PrtnCreditDemandInfoDtoFilterPaged filter);
        List<StateAssetApplicationReportDto> GetStateAssetApplicationReport(StateAssetApplicationFilter dto);
        List<OffertaCalculateInfoDto> GetOffertaCalculate(OffertaCalculateInfoDtoFilter filter);
        List<BusinessActivityTypeReportDto> GetBusinessActivityTypeReport(BusinessActivityTypeReprotFilter dto);
        List<CorruptionApplicationDto> GetAntiCorruptionByRegion(CorruptionApplicationFilterDto options);
        List<ArbitrationApplicationDto> GetArbitrationApplicationReport(ArbitrationApplicationDtoFilter filter);
        List<BusinessActivityTypeReportByRegion> GetBusinessActivityTypeReportByRegion(BusinessActivityTypeReportByRegionFilter dto);
        PagedResult<TaxCreditreportDto> GetTaxCreditReport(TaxCreditReportDtoFilterPageOptions options);
        IQueryable<TaxCreditreportDto> GetTaxCreditReport(TaxCreditReportDtoFilter filter);
        IQueryable<BankCreditApplicationReportByRegionAndDistrictDto> GetBankCreditApplicationReportByRegionAndDistrict(BankCreditApplicationReportByRegionAndDistrictDtoFilter options);
        List<PrtnCreditDemandInfoByBankDto> GetPrtnCreditDemandInfoByBank(PrtnCreditDemandInfoByBankDtoFilter filter);
        List<HrmEmployeeDocumentDto> GetReportDocumentsForHrm(HrmEmployeeDocumentDtoFilter dto);
        PrtnApplicationByContractTypeDto GetPrtnApplicationByContractType(PrtnApplicationByContractTypeDtoFilter filter);
        PrtnCertificateByContractDto GetPrtnCertificateByContract(PrtnCertificateByContractDtoFilter filter);
        EmployeeCardDto GetEmployeeCard(EmployeeCardDtoFilter dto);
        List<StaffingSinglePageReportDto> GetStaffingSingleReport(StaffingSinglePageReportDtoFilter dto);
        PagedResult<StaffingSinglePageReportDto> GetStaffingSingleReportForParent(StaffingSinglePageReportDtoFilter dto);
        List<GetSoliqReportByContractorDto> GetSoliqReportByContractor(GetSoliqReportByContractorDtoFilter options);
        // List<AppealReportDto> AppealReportByAppealType(AppealReportDtoFilter option);
        List<AppealReportByTypeReportDto> GetAppealApplicationReport(AppealReportDtoFilter filter);
        List<ClaimApplicationDto> GetClaimApplicationReport(ClaimApplicationDtoFilter filter);
        List<TadbirkorFundReportDto> GetTadbirkorFundReport(TadbirkorFundReportDtoFilter options);
        List<BojxonaImtiyozReportByContractorDto> GetBojxonaImtiyozReportByContractor(BojxonaImtiyozReportByContractorDtoFilter options);
        List<CallCenterDto> GetCallCenterByRegion(CallCenterDtoFilter dto);
        Stream SaveAsExecel(PrtnApplicationAndContractInfoDtoFilter dto);
        Stream SaveAsExcelBankCreditReport(ContractorBankCreditReportDtoFilter dto);
        Stream SaveAsExecelForSum(PrtnApplicationAndContractInfoDtoFilter dto);
        Stream SaveAsExcelSoliqReportByContractor(GetSoliqReportByContractorDtoFilter options);
        Task<List<ContractorBankCreditReportResponse>> GetBankCreditReport(ContractorBankCreditReportDtoFilter dto);

        Task<PagedResult<ContractorBankCreditReportResponse>> GetPagedBankCreditReport(ContractorBankCreditReportDtoFilterPageOptions options);
        Task<List<GetFreeAreaByInnDataDto>> GetFreeAreaFromBandlik();
        Stream SaveAsExecelForPrtnCreditDemand(PrtnCreditDemandInfoByBankDtoFilter dto);
        Stream SaveAsExecelForPrtnCreditDemandPaged(PrtnCreditDemandInfoDtoFilterPaged dto);
        Stream SaveAsExecelBojxonaImtiyozReportByContractor(BojxonaImtiyozReportByContractorDtoFilter dto);
        Stream PrtnApplicationByContractTypeExcel(PrtnApplicationByContractTypeDtoFilter dto);
	    //List<AppealReportByTypeReportDto> GetAppealReportByTypeReport(AppealReportDtoFilter dto);
		PrtnEmploymentGraphReportDto GetPrtnEmploymentGraphReport(PrtnEmploymentGraphPageOption filter, bool isPrint = false);
        Stream SaveAsExcelPrtnEmploymentGraph(PrtnEmploymentGraphPageOption dto);
        Stream SaveAsExcelPrtnBojxonaContracts(PrtnApplicationByContractTypeDtoFilter dto);
        Stream SaveAsExcelPrtnSoliqImtiyozContracts(PrtnApplicationByContractTypeDtoFilter dto);
        Stream SaveAsExcelPrtnDavAkticContract(PrtnApplicationByContractTypeDtoFilter dto);
        Stream  SaveAsExcelSummaryReportByOkedTypes(PrtnApplicationByContractTypeDtoFilter filter);
        Stream SaveAsExcelTaxReport(TaxCreditReportDtoFilter dto);
        Stream SaveAsExcelGetMemshipDocsInfo(MemshipDocsInfoDtoFilter option);
        Task<Stream> SaveAsExcelBankCreditReportAsync(ContractorBankCreditReportDtoFilter dto);
        Task<Stream> SaveAsExcelSecondBankCreditReportAsync(ContractorBankCreditReportDtoFilter dto);
        List<MemshipReportDto> GetMemshipReports1(MemshipReportDtoFilter dto);
        List<MemshipReportFuncDto> GetMemshipReports(MemshipReportDtoFilter option);
        Stream SaveAsExcelGetMemshipReport(MemshipReportDtoFilter filter);
        Stream SaveAsExcelAllIntegrationReportByContractor();
        Stream SaveAsExcelAllIntegrationReportByRegion();
        Stream SaveAsExcelAllEmployeeCountReport(AllEmployeeCountReportDto dto);
        Stream SaveAsExcelPrtnContracts(PrtnDocumentSortFilterOptions dto);
        Stream SaveAsExcelContractorFundByBank(BusinessActivityTypeReprotFilter dto);
        Stream SaveAsExcelContractorFundByRegion(BusinessActivityTypeReportByRegionFilter dto);
        Stream SaveAsExcelBankCreditePrivilegeReport(BankCreditApplicationReportByRegionAndDistrictDtoFilter dto);
        Stream SaveAsExecelForPrtnCreditBank(PrtnCreditDemandInfoByBankDtoFilter dto);
        Stream SaveAsExcelCustomsRelief(BojxonaImtiyozReportByContractorDtoFilter dto);
        PagedResult<GetTaxQqsAylanmaDto> GetTaxQqsAylanmaReport(GetTaxQqsAylanmaDtoFilter options);
        Stream SaveAsExcelStateAssetApplications(StateAssetApplicationFilter dto);
        List<StaffCountDto> GetStaffCountReport(StaffCountDtoFilter filter);
        List<StaffCountByGenderDto> GetStaffCountByGenderReport(StaffCountByGenderDtoFilter filter);
        List<AppealsSentToClaimAppDto> GetAppealsSentToClaimApplication(ClaimApplicationReportsDtoFilter filter);
        ReceivedClaimAppDto GetReceivedClaimApplication(ClaimApplicationReportsDtoFilter filter);
        List<SummaOfClaimAppDto> GetSummaOfClaimApplication(ClaimApplicationReportsDtoFilter filter);
        List<MemshipPaidReportDto> GetPaidMemshipReport(MemshipPaidReportDtoFilter options);
        Stream SaveAsExcelGetPaidMemshipReport(MemshipPaidReportDtoFilter option);
        Stream SaveAsExcelGetMemshipReportByOrganization(MemshipReportByOrganizationDtoFilter dto);
        Stream SaveAsExcelGetMemshipReportByPersonType(MemshipReportByPersonTypeFilter dto);
        (List<SmsLogReportDto>, long) GetSmsLogReportList(SmsLogReportFilterDto options);
        Stream SaveAsExcelGetSmsLog(SmsLogReportFilterDto dto);
        List<ClaimApplicationAmountDto> GetClaimApplicationAmount(ClaimApplicationAmountDtoFilter filter);
        Stream SaveAsExcelAppealsSentToClaimApplication(ClaimApplicationReportsDtoFilter dto);
        Stream SaveAsExcelReceivedClaimApplication(ClaimApplicationReportsDtoFilter dto);
        Stream SaveAsExcelSummaOfClaimApplication(ClaimApplicationReportsDtoFilter dto);
        MemshipDocsInfoReestrDto GetMemshipDocsInfoReestr(MemshipDocsInfoReestrDtoFilter options);
        List<CharterMembersRegisterReportDto> GetCharterMembersRegisterReportList(CharterMembersRegisterFilterDto options);
        Stream SaveAsExcelCharterMembersRegisterReport(CharterMembersRegisterFilterDto dto);
        PrtnApplicationByContractTypeDto GetPrtnApplicationByContractTypePaged(PrtnApplicationByContractTypeDtoFiler2 filter);
        List<GetSrvServiceInfoResponseDto> GetSrvServicesInfo(GetSrvServiceInfoRequestDto request);
        Stream SaveAsExcelGetSrvServiceInfo(GetSrvServiceInfoRequestDto request);

        Stream SaveAsExcelTaxQqsAylanmaReport(GetTaxQqsAylanmaDtoFilter option);
		Stream SaveAsExcelGetHrmCommands(HrmEmployeeDocumentDtoFilter dto);
		Stream SaveAsExcelGetStaffCountByGenderReport(StaffCountByGenderDtoFilter dto);
		Stream SaveAsExcelGetStateEmploymentReport(StaffCountDtoFilter dto);
        List<CallCenterAppealReportByOkedTypeDto> CallCenterAppealReportByOkedType(CallCenterAppealReportByOkedTypeFilter options);
        List<CallCenterReportByWeekDto> GetCallCenterReportByWeek(CallCenterReportByWeekFilterDto options);
        Stream SaveAsExcelCallCenterAppealReportByOkedType(CallCenterAppealReportByOkedTypeFilter dto);
        Stream SaveAsExcelGetCallCenterReportByWeek(CallCenterReportByWeekFilterDto dto);
        Stream SaveAsExcelGetCallCenterByRegion(CallCenterDtoFilter dto);
        Stream SaveAsExcelContractorCategoryType(ContractorCategoryDtoFilter filter);
        Task<Stream> SaveAsExecelForCollectedReport(PrtnApplicationByContractTypeDtoFilter filter);
        Task<List<PrtnReportOnProjectImplementationAndBenefitsGranted>> ReportOnProjectImplementationAndBenefitsGranted(PrtnFilterDto dto);
     //   public List<ExpiredContractorsReportDto> GetExpiredContractorsReport(PrtnDocumentSortFilterOptions options);
        PagedResult<PrtnApplicationAndContractInfoDto> GetExpiredContractorsReportPageResult(PrtnDocumentSortFilterOptions options);
        IQueryable<PrtnApplicationAndContractInfoDto> GetExpiredContractorsReportMethod(PrtnDocumentSortFilterOptions options);
        List<PrtnApplicationAndContractInfoDto> GetExpiredContractorsReport(PrtnApplicationAndContractInfoDtoFilter filter);

        Stream SaveAsExcelExpiredContractorsReport(PrtnApplicationAndContractInfoDtoFilter filter);
        Stream SaveAsExcelAllExpiredContractorsReport(PrtnDocumentSortFilterOptions options);
        List<SrvDeedDto> GetSrvDeedReport(SrvDeedListReportSortFilter filter);
        List<SrvDeedDto> GetSrvFreeDeedReport(SrvDeedListReportSortFilter filter);
        List<SrvDeedDto> GetSrvFreeDeedReportFromFunction(SrvDeedListReportSortFilter filter);
        Stream SaveAsExcelGetSrvDeedReport(SrvDeedListReportSortFilter options);
        Stream SaveAsExcelGetSrvFreeDeedReport(SrvDeedListReportSortFilter options);
        List<ClaimApplicationReportDto> ClaimApplicationReport(ClaimApplicationDtoFilter filter);
        Stream SaveAsExcelClaimApplicationReport(ClaimApplicationDtoFilter filter);

        List<MonoApplicationReportDto> MonoApplicationReport(MonoApplicationReportSortFilter filter);
		Stream MonoApplicationReportSaveExcel(MonoApplicationReportSortFilter filter);
        //PrtnApplicationByRegionDto GetPrtnApplicationByRegion(PrtnApplicationByRegionDtoFilter filter);
        List<PrtnEmployeeJobReportDto> GetPrtnEmployeeJobReport(PrtnEmployeeJobDtoFilter filter);
    }
}