using System.Collections;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using WEBASE.OfficeTools.Attributes;
using WEBASE.OfficeTools.Extensions;
using WEBASE.OfficeTools.Handlers;
using WEBASE.OfficeTools.Models;
using WEBASE.QRCode;
namespace WEBASE.OfficeTools.Factory;

public class WordFactory
{
    public static MemoryStream PrintWordDocument<T>(T model)
       where T : class
    {
        var plh = MakePlaceholders(model);
        var wordFilePath = "C:\\Users\\User\\Desktop\\AutoGeneratedTemplate.docx";
        var handler = new DocXHandler(wordFilePath, plh);
        return handler.ReplaceAll();
    }
    public static MemoryStream PrintWordDocument<T>(T model, MemoryStream wordFile)
      where T : class
    {
        var plh = MakePlaceholders(model);
        var handler = new DocXHandler(wordFile, plh);
        return handler.ReplaceAll();
    }
    public static byte[] GenerateWordTemplate<T>(T model, Placeholders? plh = null)
    where T : class
    {
        plh ??= new Placeholders();
        var type = model.GetType();
        var properties = type.GetValidProperties();
        var path = "TempDoc.docx";
        using var document = WordprocessingDocument.Create(path, WordprocessingDocumentType.Document);

        MainDocumentPart mainPart = document.AddMainDocumentPart();
        mainPart.Document = new Document();
        var body = mainPart.Document.AppendChild(new Body());
        foreach (var property in properties)
        {
            if (property.PropertyType.IsGenericType &&
               property.PropertyType.GetGenericTypeDefinition() == typeof(List<>))
            {
                AddTable(plh, body, property);

                // Need Add Temlate List approach
            }
            else
            {
                var paragraphItem = new Paragraph();
                paragraphItem.Append(
                    new Run(
                        new SdtCell(
                            new Text(
                                plh.TextPlaceholderStartTag
                                + property.Name
                                + plh.TextPlaceholderEndTag
                                )
                            )
                        )
                    );
                body.AppendChild(paragraphItem);
                //}    
            }
        }
        var paragraph = new Paragraph();
        var qrProp = properties.FirstOrDefault(pr => pr.PropertyType == typeof(QrCodeModel));
        if (qrProp != null)
            paragraph.AppendChild(new Run(new SdtCell(new Text(plh.ImagePlaceholderStartTag + qrProp.Name + plh.ImagePlaceholderEndTag))));
        body.AppendChild(paragraph);
        //var pdf=document.
        document.Save();
        //document.SaveAs("C:\\Users\\User\\Desktop\\AutoSavedDoc.pdf");
        document.Close();
        //Console.WriteLine();
        //Console.WriteLine("Go Go Go Go Go Go Go Go ");
        //Console.WriteLine();
        var file = File.ReadAllBytes(path);
        File.Delete(path);
        return file;
    }

    private static void AddTable(Placeholders? placeholders, Body body, System.Reflection.PropertyInfo? property)
    {
        var paragraphItem = new Paragraph();
        paragraphItem.Append(new Run(new Text(property.Name)));
        body.AppendChild(paragraphItem);


        var listType = property.PropertyType.GetGenericArguments()[0];

        var itemProperties = listType.GetValidProperties();

        var grid = new TableGrid();
        foreach (var item in itemProperties)
        {
            grid.Append(new GridColumn());
        }
        var tableProperties = new TableProperties()
        {
            TableBorders = new TableBorders
            {
                TopBorder = new TopBorder { Val = BorderValues.Single },
                BottomBorder = new BottomBorder { Val = BorderValues.Single },
                LeftBorder = new LeftBorder { Val = BorderValues.Single },
                RightBorder = new RightBorder { Val = BorderValues.Single },
                InsideHorizontalBorder = new InsideHorizontalBorder { Val = BorderValues.Single },
                InsideVerticalBorder = new InsideVerticalBorder { Val = BorderValues.Single }
            },
        };

        var layout = new TableLayout();
        layout.Type = TableLayoutValues.Autofit;

        tableProperties.Append(layout);
        var table = new Table();
        table.Append(tableProperties);
        table.Append(grid);
        var row1 = new TableRow();

        foreach (var itemProperty in itemProperties)
        {
            var headerText = new Run(new Text("Header."));
            var runProp = new RunProperties();
            runProp.Append(new Bold());
            headerText.Append(runProp);

            var cellParagraph = new Paragraph();
            cellParagraph.Append(headerText);
            var cell = new TableCell(cellParagraph);

            row1.Append(cell);
        }
        table.Append(row1);

        var row2 = new TableRow();
        foreach (var itemProperty in itemProperties)
        {
            var cellParagraph = new Paragraph();
            cellParagraph.Append(
                new Run(
                    new SdtCell(
                        new Text(
                            placeholders.TablePlaceholderStartTag
                            + itemProperty.Name
                            + placeholders.TablePlaceholderEndTag
                            )
                        )
                    )
                );
            var cell = new TableCell(cellParagraph);

            TableCellProperties tableCellProperties = new TableCellProperties();
            TableCellWidth tableCellWidth = new TableCellWidth() { Width = "0", Type = TableWidthUnitValues.Auto };
            tableCellProperties.Append(tableCellWidth);
            cell.Append(tableCellProperties);
            row2.Append(cell);
        }
        table.Append(row2);

        body.Append(table);
    }

    public static Placeholders MakePlaceholders<T>(T model, string numberFormat = null)
       where T : class
    {
        var placeholders = new Placeholders();
        var type = model.GetType();
        var properties = type.GetProperties()
            .Where(p => !(p.GetCustomAttributes(typeof(IgnoreWordProperty), true).Any()));

        var properties2 = type.GetProperties();

        foreach (var property in properties)
        {
            if (property.PropertyType.IsGenericType &&
               property.PropertyType.GetGenericTypeDefinition() == typeof(List<>))
            {
                var listType = property.PropertyType.GetGenericArguments()[0];

                //var itemProperties = listType.GetValidProperties();
                Dictionary<string, List<string>> dic = new();
                var list = (IEnumerable?)property.GetValue(model);
                var plhsForTemplate = new List<Placeholders>();
                if (list != null)
                {
                    foreach (var listItem in list)
                    {
                        var itemProperties = listItem.GetType().GetProperties();
                        var itemPlh = new Placeholders();
                        foreach (var itemProperty in itemProperties)
                        {
                            if (!dic.ContainsKey(itemProperty.Name))
                                dic.Add(itemProperty.Name, new() { itemProperty.GetValue(listItem)?.FormattedToString( numberFormat) ?? "-" });
                            else
                                dic[itemProperty.Name].Add(itemProperty.GetValue(listItem)?.FormattedToString(numberFormat) ?? "-");

                            if (itemProperty.PropertyType == typeof(QrCodeModel))
                                AddQrCodeImage(listItem, itemPlh, itemProperty);
                            itemPlh.TextPlaceholders.Add(itemProperty.Name, itemProperty.GetValue(listItem)?.FormattedToString(numberFormat) ?? "-");
                        }
                        plhsForTemplate.Add(itemPlh);
                    }
                }
                placeholders.TablePlaceholders.Add(dic);

                placeholders.TemplateListPlaceholders.TryAdd(property.Name, plhsForTemplate);
            }
            else if (property.PropertyType == typeof(QrCodeModel))

                AddQrCodeImage(model, placeholders, property);

            else
            {
                placeholders.TextPlaceholders.Add(property.Name, property.GetValue(model)?.FormattedToString(numberFormat) ?? "-");
            }
        }

        return placeholders;
    }

    private static void AddQrCodeImage<T>(T model, Placeholders placeholders, System.Reflection.PropertyInfo? property) where T : class
    {
        var qrModel = (QrCodeModel)property.GetValue(model);
        if (qrModel == null || qrModel.Text == null)
        {
            return;
        }
        var qrCode = new MemoryStream(QRCodeHelper.GeneratePng(qrModel.Text, width: qrModel.Width, height: qrModel.Height));
        placeholders.ImagePlaceholders.Add(property.Name, new()
        {
            Dpi = qrModel.Dpi,
            MemStream = qrCode
        });
    }
}
