namespace SspUis.Core;

public class NumberTemplateDocumentConst
{
    public const string DOC_APPLICATION = "DOC_APPLICATION";
    public const string DOC_APPEAL_APPLICATION = "DOC_APPEAL_APPLICATION";
    public const string DOC_PRTN_CONTRACT = "DOC_PRTN_CONTRACT";
    public const string DOC_PRTN_CERTIFICATE = "DOC_PRTN_CERTIFICATE";
    public const string DOC_STAFFING = "DOC_STAFFING";
    public const string DOC_STAFFING_TEMPLATE = "DOC_STAFFING_TEMPLATE";
    public const string DOC_PROPOSAL = "DOC_PROPOSAL";
    public const string DOC_ORDER_TO_SEND_BUSINESS_TRIP = "DOC_ORDER_TO_SEND_BUSINESS_TRIP";
    public const string DOC_WORK_DAY_OFF = "DOC_WORK_DAY_OFF";
    public const string DOC_RECALL_LEAVE = "DOC_RECALL_LEAVE";
    public const string DOC_APPOINT_EMPLOYEE = "DOC_APPOINT_EMPLOYEE";
    public const string DOC_EXECUTION_APPLICATION = "DOC_EXECUTION_APPLICATION";
    public const string DOC_EMPLOYEE_lEAVE_ORDER = "DOC_EMPLOYEE_lEAVE_ORDER";
    public const string DOC_EMPLOYEE_SEND_TRAIN = "DOC_EMPLOYEE_SEND_TRAIN";
    public const string DOC_EMPLOYEE_SEND_STUDY = "DOC_EMPLOYEE_SEND_STUDY";
    public const string DOC_EMPLOYEE_SICK_LEAVE = "DOC_EMPLOYEE_SICK_LEAVE";
    public const string DOC_MASS_PLANNED_CALCULATION = "DOC_MASS_PLANNED_CALCULATION";
    public const string DOC_MEMSHIP_YEARLY_PLAN = "DOC_MEMSHIP_YEARLY_PLAN";
    public const string DOC_KPI_RATING_EMPLOYEE = "DOC_KPI_RATING_EMPLOYEE";
    public const string DOC_KPI_GRATING = "DOC_KPI_GRATING";
    public const string DOC_KPI_PLAN_FOR_EMPLOYEE = "DOC_KPI_PLAN_FOR_EMPLOYEE";
    public const string DOC_SRV_APPLICATION_YEARLY_PLAN = "DOC_SRV_APPLICATION_YEARLY_PLAN";
    public const string DOC_MEMSHIP_CERTIFICATE = "DOC_MEMSHIP_CERTIFICATE";
    public const string DOC_MEMSHIP_CONTRACT = "DOC_MEMSHIP_CONTRACT";
    public const string DOC_SERVICE_DEED = "DOC_SERVICE_DEED";
    public const string ADDITIONAL_AGREEMENT = "ADDITIONAL_AGREEMENT";
    public const string DOC_PLANNED_CALCULATION = "DOC_PLANNED_CALCULATION";
    public const string DOC_MEMSHIP_APPLICATION = "DOC_MEMSHIP_APPLICATION";
    public const string DOC_DUAL_EDU_APPLICATION = "DOC_DUAL_EDU_APPLICATION";
    public const string DOC_JOIN_ANTI_CORRUPTION_APPLICATION = "DOC_JOIN_ANTI_CORRUPTION_APPLICATION";
    public const string DOC_MEMSHIP_PAYMENT_ORDER = "DOC_MEMSHIP_PAYMENT_ORDER";

    public const string DOC_SERVICE_PRICE = "DOC_SERVICE_PRICE";
    public const string DOC_COMPLETE_SERVICE = "DOC_COMPLETE_SERVICE";
    public const string DOC_SERVICE_CONTRACT = "DOC_SERVICE_CONTRACT";
    public const string DOC_CONDITATES_COMFIRMED = "DOC_CONDITATES_COMFIRMED";
    public const string DOC_ARBITRATION_COURT_APPLICATION = "ARBITRATION_COURT_APPLICATION";
    public const string DOC_ARBITRATION_DISCUSSION = "DOC_ARBITRATION_DISCUSSION";
    public const string DOC_ARBITRATION_RESULT = "DOC_ARBITRATION_RESULT";
    public const string DOC_ARBITRATION_DELAY = "DOC_ARBITRATION_DELAY";
    public const string DOC_TIMESHEET = "DOC_TIMESHEET";
    public const string DOC_MEMSHIP_NEW_CONTRACTOR = "DOC_MEMSHIP_NEW_CONTRACTOR";
    public const string DOC_APPLICATION_FOR_COURT = "DOC_APPLICATION_FOR_COURT";

}
