using System.IO;
using System.Threading;

namespace WEBASE.Storage;

public class StaticFileConst
{
    public class HtmlTemplate
    {
        private static string FOLDER = "htmltemplates";
        public static string GetFileName(string culture, string fileName) => Path.Combine(FOLDER, culture, fileName);
    }
    public class WordTemplate
    {
        private static string FOLDER = "wordtemplates";
        public static readonly string MEMSHIP_APPLICATION = "MemshipApplication.docx";
        public static readonly string MEMSHIP_CONTRACT = "MemshipContract.docx";
        public static readonly string ADDITIONAL_AGREEMENT = "AdditionalAgreement.docx";
        public static readonly string MEMSHIP_CONTRACT_FREE = "MemshipContractFree.docx";
        public static readonly string MEMSHIP_CERTIFICATE = "MemshipCertificate.docx";
        public static readonly string MEMSHIP_CERTIFICATE_Cancel = "MemshipCertificateCancel.docx";
        public static readonly string MEMSHIP_CERTIFICATE_ERROR = "MemshipCertificateError.docx";
        public static readonly string CLAIM_APPLICATION_ADMINISTRATIVE_COURT = "ClaimApplication1.docx";
        public static readonly string CLAIM_APPLICATION_ADMINISTRATIVE_COURT_SSP = "ClaimApplicationRespSSP.docx";
        public static readonly string CLAIM_APPLICATION_ADMINISTRATIVE_COURT_1SSP = "ClaimApplicationSSP1.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION = "ClaimApplication25.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_TOSHKENT_SHAHRI = "ClaimApplicationToshkentShahri.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_TOSHKENT_VILOYATI = "ClaimApplicationToshkentViloyati.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_XORAZM = "ClaimApplicationXorazm.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_SURXONDARYO = "ClaimApplicationSurxondaryo.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_SIRDARYO = "ClaimApplicationSirdaryo.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_SAMARQAND = "ClaimApplicationSamarqand.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_QORAQALPOGISTON = "ClaimApplicationQoraqalpogiston.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_QASHQADARYO = "ClaimApplicationQashqadaryo.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_NAVOIY = "ClaimApplicationNavoiy.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_NAMANGAN = "ClaimApplicationNamangan.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_JIZZAX = "ClaimApplicationJizzax.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_FARGONA = "ClaimApplicationFargona.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_BUXORO = "ClaimApplicationBuxoro.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_ANDIJON = "ClaimApplicationAndijon.docx";
        public static readonly string CLAIM_0R_COUNTERCLAIM_APPLICATION_SSP = "ClaimApplication26.docx";
        public static readonly string CLAIM_APPLICATION_APILATION_OR_CASSATION = "ClaimApplication34.docx";
        public static readonly string MEDIATION = "Mediation.docx";
		#region mediationPlan
		public static readonly string MEDIATION_PLAN = "MediationPlan.docx";

		public static readonly string MEDIATION_PLAN_SSP = "MediationPlanRespSSP.docx";
		public static readonly string MEDIATION_PLAN_XORAZM = "MediationPlanXorazm.docx";
		public static readonly string MEDIATION_PLAN_ANDIJON = "MediationPlanAndijon.docx";
		public static readonly string MEDIATION_PLAN_BUXORO = "MediationPlanBuxoro.docx";
		public static readonly string MEDIATION_PLAN_FARGONA = "MediationPlanFargona.docx";
		public static readonly string MEDIATION_PLAN_JIZZAX = "MediationPlanJizzax.docx";
		public static readonly string MEDIATION_PLAN_NAMANGAN = "MediationPlanNamangan.docx";
		public static readonly string MEDIATION_PLAN_NAVOIY = "MediationPlanNavoiy.docx";
		public static readonly string MEDIATION_PLAN_QASHQADARYO = "MediationPlanQashqadaryo.docx";
		public static readonly string MEDIATION_PLAN_QORAQALPOQ = "MediationPlanQoraqalpogiston.docx";
		public static readonly string MEDIATION_PLAN_SAMARQAND = "MediationPlanSamarqand.docx";
		public static readonly string MEDIATION_PLAN_SIRDARYO = "MediationPlanSirdaryo.docx";
		public static readonly string MEDIATION_PLAN_SURXONDARYO = "MediationPlanSurxondaryo.docx";
		public static readonly string MEDIATION_PLAN_TOSHKENT = "MediationPlanToshkentShaxri.docx";
		public static readonly string MEDIATION_PLAN_TOSHKENT_VIL = "MediationPlanToshkentViloyati.docx";
		#endregion
		public static readonly string JOIN_ANTICORRUPTION_APPLICATION = "JoinAntiCorruptionApplication.docx";
        public static readonly string JOIN_ANTICORRUPTION_CERTIFICATE = "JoinAntiCorruptionCertificate.docx";
        public static readonly string APPLICATION_FOR_COURT = "ApplicationForCourt.docx";
        public static readonly string BANK_MEDIATION_DOCUMENT = "BankMediationDocument.docx";
        public static readonly string XALQ_BANK_MEDIATION_DOCUMENT = "XalqBankMediationDocument.docx";
        public static readonly string EMPLOYEE_CV = "EmployeeCV.docx";
        public static readonly string SERVICE_APPLICATION = "SrvApplication.docx";
        public static readonly string SERVICE_CONTRACT = "ServiceCon.docx";
        public static readonly string EMPLOYEE_LEAVE_ORDER = "EmployeeLeaveOrder.docx";
        public static readonly string RE_CALL_LEAVE = "ReCallLeave.docx";
        public static readonly string APPOINT_EMPLOYEE_HIRE = "AppointEmployeeHire.docx";
        public static readonly string APPOINT_EMPLOYEE_HIRE_IS_PROBARATION = "AppointEmployeeHireIsProbaration.docx";
        public static readonly string APPOINT_EMPLOYEE_TRANSFER = "AppointEmployeeTransfer.docx";
        public static readonly string APPOINT_EMPLOYEE_DISMISSAL = "AppointEmployeeDismissal.docx";
        public static readonly string APPEAL_APPLICATION = "AppealApplication.docx";
        public static readonly string APPEAL_CALLCENTR = "AppealCallCentr.docx";
        public static readonly string EMPLOYEE_SEND_BUSINESS_TRIP = "EmployeeSendBusinessTrip.docx";
        public static readonly string EMPLOYEE_MOD_HELP = "EmployeeModHelp.docx";
        public static readonly string EMPLOYEE_LEAVE_FOR_CHILD_CARE = "EmployeeLeaveForChildCare.docx";
        public static readonly string EMPLOYEE_LEAVE_ORDER_IS_WITH_OUT_PAY = "EmployeeLeaveOrderIsWithOutPay.docx";
        public static readonly string EMPLOYEE_LEAVE_ORDER_IS_WITH_PAY = "EmployeeLeaveOrderIsWithPay.docx";
        public static readonly string DOWNLOAD_TEMP = "DownloadTemp.docx";
        public static readonly string SRV_DEED_WITH_PAY = "SrvDeedWithPay.docx";
        public static readonly string CHASTISEMENT = "Chastisement.docx";
        public static readonly string DUAL_CONTRACT = "DualContract.docx";
        public static readonly string APPOINT_EMPLOYEE_COMMON = "AppointEmployeeCommon.docx";
        public static readonly string JOIN_ANTI_CORRUPTION_RESULT = "JoinAntiCorruptionResult.docx";
        public static string GetFileName(string culture, string fileName) => Path.Combine(FOLDER, culture, fileName);
    }
    public class ExcelTemplate
    {
        private static string FOLDER = "exceltemplates";
        public static string GetFileName(string culture, string fileName) => Path.Combine(FOLDER, culture, fileName);
    }
    public class Report
    {
        private static string FOLDER = "exceltemplates";
        public static readonly string APPLICATION_STATUS = "ApplicationStatus.xlsx";
        public static readonly string APPLICATION_PROCESSINFO = "ApplicationProcessInfo.xlsx";
        public static readonly string CONTRACTS_INFO = "ContractsInfo.xlsx";
        public static readonly string CONTRACTS_PROCESS_INFO = "ContractsFullInfo.xlsx";
        public static readonly string USER_LIST = "user_list.xlsx";
        public static readonly string REQUEST_LIST = "Request.xlsx";
        public static readonly string POSTPONEMEBT_LIST = "Postponement.xlsx";
        public static readonly string REQUESTFORCENTRALAPPARAT_LIST = "RequestForCentralApparat.xlsx";
        public static readonly string INSPECTIONRESULT_LIST = "Inspectionresult.xlsx";
        public static readonly string INSPECTIONRESULTBOOK_LIST = "";
        public static readonly string INSPECTIONRESULTBOOKCREATE_LIST = "Inspectionbookofcontract.xlsx";
        public static readonly string ATTESTATION_LIST = "AttestationStatus.xlsx";
        public static readonly string ATTESTATIONCREATE_LIST = "AttationCreate.xlsx";
        public static readonly string OKED_LIST = "Oked.xlsx";
        public static readonly string CHECKINGQUIZ_LIST = "CheckingQuiz.xlsx";
        public static readonly string INSPECTIONBOOKOFCONTRACT_LIST = "InspectionBookOfContractor.xlsx";
        public static readonly string INSPECTIONBOOKOFCONTRACTFORVIEW_LIST = "InspectionBookOfContractorForView.xlsx";
        public static readonly string ORGANIZATIOM_LIST = "Organization.xlsx";
        public static readonly string APPLICATION_LIST = "ApplicationTemplate.xlsx";
        public static readonly string PRTN_CREDIT_DEMAND_LIST = "PrtnCreditDemandTemplate.xlsx";
        public static readonly string PRNTCERTIFICATE_LIST = "PrtnCertificateTemplate.xlsx";
        public static readonly string PRNTCONTRACT_LIST = "PrtnContractTemplate.xlsx";
        public static readonly string PRNT_APPLICATION_AND_CONTRACT_INFO_LIST = "PrtnApplicationAndContractInfoTemplate.xlsx";
        public static readonly string PRINT_FROM_BOJXONA_LIST = "PrintFromBojxona.xlsx";
        public static readonly string PRNT_APPLICATION_AND_CONTRACT_FOR_SUM_LIST = "PrtnApplicationAndContractForSumTemplate.xlsx";
        public static readonly string PRNT_CREDIT_DEMAND_LIST= "PrtnCreditDemand.xlsx";
        public static readonly string PRNT_CREDIT_DEMAND_LIST_PAGED= "PrtnCreditDemandPaged.xlsx";
        public static readonly string PRNT_CREDIT_BANK_LIST= "PrtnCreditBank.xlsx";
        public static readonly string BOJXONA_IMTIYOZ_REPORT_BY_CONTRACTOR = "BojxonaImtiyozReportByContractor.xlsx";
        public static readonly string PRNT_APPLICATION_BY_CONTRACT_TYPE = "PrtnApplicationByContractType.xlsx";
        public static readonly string EMPLOYEEUSER_LIST = "Users.xlsx";
        public static readonly string EMPLOYEEUSERKADIR_LIST = "Userskadir.xlsx";
        public static readonly string ATTESTATION_USERS = "AttestationUsers.xlsx";
        public static readonly string POSITIONS = "Position.xlsx";
        public static readonly string CONTROLFUNCTION = "ControlFunction.xlsx";
        public static readonly string MANDATORYREUIREMENT = "MandatoryRequirement.xlsx";
        public static readonly string PROPHYLAXIS_LIST = "Prophylaxis.xlsx";
        public static readonly string INSPECTIONCONCLUSION_LIST = "InspectionConclusion.xlsx";
        public static readonly string INSPECTIONCONCLUSIONFORVIEW_LIST = "InspectionConclusionForView.xlsx";
        public static readonly string REPORT1_LIST = "Report1.xlsx";
        public static readonly string REPORT2_LIST = "Report2.xlsx";
        public static readonly string REPORT3_LIST = "Report3.xlsx";
        public static readonly string REPORT4_LIST = "Report4.xlsx";
        public static readonly string REPORT5_LIST = "Report5.xlsx";
        public static readonly string REPORT6_LIST = "Report6.xlsx";
        public static readonly string REPORT7_LIST = "Report7.xlsx";
        public static readonly string REPORT8_LIST = "Report8.xlsx";
        public static readonly string PROPOSAL_LIST = "Proposal.xlsx";
        public static readonly string PRINT_GRAPH_EXCEL_LIST = "PrintGraphExcel.xlsx";
        public static readonly string DOC_SRV_APPLICATION_LIST = "SrvApplicationView.xlsx";
        public static readonly string DOC_APPEAL_APPLICATION_LIST = "AppealApplicationView.xlsx";
        public static readonly string SOLIQ_REPORT_BY_CONTRACTOR = "SoliqReportByContractor.xlsx";
        public static readonly string EMPLOYEE_COUNT_BY_REGION_LIST = "SaveAsExcelAllIntegrationReportByRegion.xlsx";
        public static readonly string REPORT_PARTNER_EMPLOYMENT_GRAPH = "EmploymentGraph.xlsx";
        public static readonly string REPORT_BANK_CREDIT = "BankCreditReport.xlsx";
        public static readonly string REPORT_BOJXONA_IMTIYOZ = "BojxonaImtiyoz.xlsx";
        public static readonly string REPORT_SOLIQ_IMTIYOZ = "SoliqImtiyoz.xlsx";
        public static readonly string REPORT_DAVAKTIV_IMTIYOZ = "DavaktivImtiyoz.xlsx";
        public static readonly string REPORT_FUND_IMTIYOZ = "jamgarma.xlsx";
        public static readonly string REPORT_HRM_EMPLOYEE_ACTIVITY = "HrmEmployeeActivityReportTemplate.xlsx";
        public static readonly string REPORT_TAX_IMTIYOZ = "SoliqImtiyozlari.xlsx";
        public static readonly string REPORT_TAX_MOLMULK_SOLIQ = "MolMulkSoliqImtiyozi.xlsx";
        public static readonly string REPORT_TAX_YER_SOLIQ = "YerSoliqImtiyozi.xlsx";
        public static readonly string REPORT_TAX_DAROMAD_SOLIQ = "DaromadSoliqImtiyozi.xlsx";
        public static readonly string REPORT_TAX_IJTIMOIY_SOLIQ = "IjtimoiySoliqImtiyozi.xlsx";
        public static readonly string MEMSHIP_APPLICATION = "MemshipApplication.xlsx";
        public static readonly string MEMSHIP_CONTRACT = "MemshipContract.xlsx";
        public static readonly string REPORT_MEMSHIP = "ReportMemship.xlsx";
        public static readonly string MEMSHIP_CERTIFICATE = "MemshipCertificate.xlsx";
        public static readonly string REPORT_BANK_TEZKOR_HISOBOT = "BankTezkorHisoboti.xlsx";
        public static readonly string REPORT_BANK_CREDITE_PRIVILEGE = "BankKreditImtiyozHisoboti.xlsx";
        public static readonly string REPORT_TABDIRKOR_DASTUR_HISOBOT = "TadbirkorDasturBankReport.xlsx";
        public static readonly string REPORT_PRTN_CONTRACT = "hamkorlik.xlsx";
        public static readonly string REPORT_CONTRACTOR_FUND_BYBANK = "TadbirkorJamg'armasi.xlsx";
        public static readonly string REPORT_CONTRACTOR_FUND_BYREGION = "TadbirkorJamg'armasiViloyatlarKesimida.xlsx";
        public static readonly string REPORT_MEMSHIPBYMONTH = "MemshipReportByMonth.xlsx";
        public static readonly string BOJXONE_IMTIYOZI = "BojxonaImtiyozlari.xlsx";
        public static readonly string BOJXONE_IMTIYOZITAP2 = "BojxonaImtiyozlariTap2.xlsx";
        public static readonly string BOJXONE_IMTIYOZITAP3 = "BojxonaImtiyozlariTap3.xlsx";
        public static readonly string REPORT_DAVAKTIV = "DavlatAktivlari.xlsx";
        public static readonly string REPORT_PAID_MEMSHIP = "PaidMemshipReport.xlsx";
        public static readonly string REPORT_MEMSHIP_REPORT_BY_ORGANIZATION = "MemshipReportByOrganizations.xlsx";
        public static readonly string REPORT_MEMSHIP_REPORT_BY_PERSON_TYPE = "MemshipReportByPersonType.xlsx";
        public static readonly string ALL_INTEGRATION_REPORT_BY_CONTRACTOR = "AllIntegrationReportByContractor.xlsx";
        public static readonly string SEND_SMS_REPORT = "sms-config-excel.xlsx";
        public static readonly string APPEALS_SENT_TO_CLAIM_APPLICATION = "AppealsSentToClaimApplication.xlsx";
        public static readonly string RECEIVED_CLAIM_APPLICATION = "ReceivedClaimApplication.xlsx";
        public static readonly string SUMMA_OF_CLAIM_APPLICATION = "SummaOfClaimApplication.xlsx";
        public static readonly string CHARTER_MEMBERS_REGISTER = "��������������p������.xlsx";
        public static readonly string REPORT_SRV_SERVICE_GET_INFO = "Xizmatlar.xlsx";
        public static readonly string MONO_APPLICATION_REPORT = "monoapplication.xlsx";
        public static readonly string REPORT_SRV_SERVICE_GET_FREE_INFO = "BepulXizmatlar.xlsx";
        public static readonly string REPORT_EMPLOYEE_COUNT = "EmployeeCountReport.xlsx";
        public static readonly string EMPLOYEE_TURNSTILE_REPORT = "EmployeeTurnstileReport.xlsx";
        public static readonly string SRV_DEED = "SrvDeed.xlsx";
        public static readonly string REPORT_TAX_QQS_AYLANMA = "TaxQqsAylanmaReport.xlsx";
        public static readonly string HRM_COMMANDS_REPORT = "HrmCommandsReport.xlsx";
        public static readonly string REPORT_HRM_ON_STATE_UNITS = "ReportHrmOnStateUnits.xlsx";
        public static readonly string HRM_GET_STAFF_COUNT_BY_GENDER_REPORT = "HrmGetStaffCountByGenderReport.xlsx";
        public static readonly string HRM_STATE_EMPLOYMENT_REPORT = "HrmStateEmploymentReport.xlsx";
        public static readonly string TURNSTILE_REPORT_ON_EMPLOYEE = "Turnstile_report_on_employee.xlsx";
        public static readonly string SUMMARY_REPORT_BY_OKED_TYPES = "SummaryReportByOkedTypes.xlsx";
        public static readonly string FOR_GET_LIST_MEMSHIP_PAYMENT_ORDER = "ForGetListMemshipPaymentOrder.xlsx";
        public static readonly string SAVE_AS_EXCEL_CALL_CENTER_APPEAL_REPORT_BY_OKED_TYPE = "SaveAsExcelCallCenterAppealReportByOkedType.xlsx";
        public static readonly string SAVE_AS_EXCEL_CALL_CENTER_APPEAL_REPORT_BY_OKED = "SaveAsExcelCallCenterAppealReportByOked.xlsx";
        public static readonly string SAVE_AS_EXCEL_CALL_CENTER_REPORT_BY_WEEK = "SaveAsExcelCallCenterReportByWeek.xlsx";
        public static readonly string SAVE_AS_EXCEL_GET_CALL_CENTER_BY_REGION = "SaveAsExcelGetCallCenterByRegion.xlsx";
        public static readonly string SAVE_AS_EXCEL_GET_CALL_CENTER_BY_PHYSICAL_TYPE = "SaveAsExcelGetCallCenterByPhysicalType.xlsx";
        public static readonly string SAVE_AS_EXCEL_GET_CONTRACTOR_CATEGORY_TYPE = "GetContractorCategoryTypeTemplate.xlsx";
        public static readonly string TABEL_TEMPLATE = "TabelTemplate.xlsx";
        public static readonly string COLLECTED_REPORTS = "Collect.xlsx";
        public static readonly string Expired_Execution_Report = "ijrotemplate.xlsx";
        public static readonly string DEED_SWOT_REPORT = "SwotReport.xlsx";
        public static readonly string DEED_FREE_SWOT_REPORT = "SwotReportFree.xlsx";
        public static readonly string XududiyKPI = "XududiyBoshqarmalarKPIv001.xlsx";
        public static readonly string CLAIM_APPLICATION_REPORT = "ClaimReports.xlsx";
        public static readonly string DUAL_APPLICATION_GETLIST = "DualApplicationTemplate.xlsx";
        public static string GetFileName(string templateName) => Path.Combine(FOLDER,templateName);
    }
}