using Microsoft.AspNetCore.Mvc;
using SspUis.BizLogicLayer;
using SspUis.DataLayer.Repositories;
using WEBASE.AspNet;
using WEBASE.Models;
using WEBASE.Storage;

namespace SspUis.WebApi.Controllers;

[ApiController]
[Route("[controller]/[action]")]
public class DocumentPrintController : WebaseController
{
    private readonly IDocumentPrintService _service;
    public DocumentPrintController(
        IDocumentPrintService service)
        : base(AppSettings.Instance.ControllerConfig)
    {
        _service = service;
    }

    [HttpGet]
    [AllowAnonymous]
    [ProducesResponseType(typeof(SelectList<int>), 200)]
    public IActionResult SelectList()
    {
        return Ok(_service.SelectList());
    }

    [HttpGet]
    [AllowAnonymous]
    [ProducesResponseType(200)]
    public async ValueTask<IActionResult> GenerateWord(int tableId)
    {
        if (ModelState.IsValid)
        {
            var bytes = await _service.GenerateWord(tableId);

            if (_service.IsValid)
                return File(bytes, "application/msword", fileDownloadName: "AutoGeneratedTemplate.docx");

            _service.CopyErrorsToModelState(ModelState);
        }

        return ValidationProblem(ModelState);
    }

    [HttpPost]
    //[ServiceFilter(typeof(UploadFileAttribute))]
    [ProducesResponseType(typeof(IEnumerable<CreateDocumentTempleteFileDlDto>), 200)]
    public IActionResult UploadFile(IFormFile files)
    {
        if (ModelState.IsValid)
        {
            StorageFile dto = new StorageFile(files.FileName, files.OpenReadStream());
            var result = _service.UploadTemplateFile(dto);

            if (_service.IsValid)
                return Ok(result);

            _service.CopyErrorsToModelState(ModelState);
        }

        return ValidationProblem(ModelState);
    }

    [HttpPost]
    [ProducesResponseType(typeof(HaveId<Guid>), 200)]
    public IActionResult SaveTemplate(CreateDocumentTempleteFileDlDto dto)
    {
        if (ModelState.IsValid)
        {
            _service.SaveTemplate(dto);

            if (_service.IsValid)
                return Ok();

            _service.CopyErrorsToModelState(ModelState);
        }

        return ValidationProblem(ModelState);
    }

    //[HttpGet]
    //[AllowAnonymous]
    //[ProducesResponseType(200)]
    //public async ValueTask<IActionResult> Print(int id)
    //{
    //    if (ModelState.IsValid)
    //    {
    //        var bytes = await _service.Print(id);

    //        if (_service.IsValid)
    //            return File(bytes, "application/msword", fileDownloadName: "AutoGeneratedTemplate.docx");

    //        _service.CopyErrorsToModelState(ModelState);
    //    }

    //    return ValidationProblem(ModelState);
    //}

}
